import os
import asyncio
import logging
from fastapi import FastAPI, Depends, BackgroundTasks, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from pathlib import Path
from pydantic import BaseModel

from app.database import init_db, get_db, MediaFile, AuditJob, AuditResult, JobStatus, FileStatus
from app.queue_manager import worker
from app.scanner import MediaScanner
from app.plex_client import PlexClient

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger("main")

app = FastAPI(title="PlexScraper Media Verification Service")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Configuration values
SCAN_PATHS = os.environ.get("SCAN_PATHS", "./media").split(",")
WORKSPACE_ROOT = os.environ.get("WORKSPACE_ROOT", ".")

# Create directories if they do not exist
Path(WORKSPACE_ROOT).mkdir(parents=True, exist_ok=True)
for path in SCAN_PATHS:
    if path:
        Path(path).mkdir(parents=True, exist_ok=True)

# Mount Static assets
# Keyframes and audio clips generated by the media processor reside inside workspace/processed_media
processed_media_path = Path(WORKSPACE_ROOT) / "processed_media"
processed_media_path.mkdir(exist_ok=True)
(processed_media_path / "keyframes").mkdir(exist_ok=True)
(processed_media_path / "audio").mkdir(exist_ok=True)

app.mount("/static/media", StaticFiles(directory=str(processed_media_path)), name="media")

# We will mount dashboard UI files inside app/static
app_static_path = Path(__file__).parent / "static"
app_static_path.mkdir(exist_ok=True)

class ScanRequest(BaseModel):
    paths: list[str] | None = None

@app.on_event("startup")
def startup_event():
    init_db()
    worker.start()
    logger.info("Database initialized and queue worker spawned.")

@app.on_event("shutdown")
def shutdown_event():
    worker.stop()
    logger.info("Queue worker stopped.")

@app.get("/api/status")
def get_service_status():
    """Gets general statistics and pipeline state."""
    db = SessionLocal()
    try:
        total_files = db.query(MediaFile).count()
        verified_files = db.query(MediaFile).filter(MediaFile.status == FileStatus.VERIFIED).count()
        flagged_files = db.query(MediaFile).filter(MediaFile.status.like("FLAGGED_%")).count()
        pending_jobs = db.query(AuditJob).filter(AuditJob.status == JobStatus.PENDING).count()
        
        current_job = db.query(AuditJob).filter(AuditJob.status == JobStatus.PROCESSING).first()
        active_filename = current_job.media_file.filename if current_job else None

        return {
            "is_running": worker.is_running,
            "is_paused": worker.is_paused,
            "total_files": total_files,
            "verified_files": verified_files,
            "flagged_files": flagged_files,
            "pending_jobs_count": pending_jobs,
            "active_job": {
                "id": current_job.id if current_job else None,
                "filename": active_filename
            } if current_job else None
        }
    finally:
        db.close()

@app.post("/api/pipeline/pause")
def pause_pipeline():
    worker.pause()
    return {"message": "Pipeline paused."}

@app.post("/api/pipeline/resume")
def resume_pipeline():
    worker.resume()
    return {"message": "Pipeline resumed."}

@app.post("/api/pipeline/scan")
def trigger_filesystem_scan(request: ScanRequest = None, db: Session = Depends(get_db)):
    """Triggers crawler to scan designated folders for new files."""
    paths = request.paths if request and request.paths else SCAN_PATHS
    scanner = MediaScanner(media_directories=paths)
    new_files = scanner.scan_and_register_files(db)
    
    # Enrich metadata from Plex if configured
    plex = PlexClient()
    new_media_records = db.query(MediaFile).filter(MediaFile.plex_rating_key == None).all()
    for item in new_media_records:
        duration, rating_key = plex.get_duration_and_rating_key(item.filepath)
        if duration:
            item.expected_duration = duration
            item.plex_rating_key = rating_key
    db.commit()

    return {"message": f"Scan completed. Discovered and queued {new_files} new files."}

@app.get("/api/files")
def get_files(status: str | None = None, db: Session = Depends(get_db)):
    """Retrieves all tracked media files."""
    query = db.query(MediaFile)
    if status:
        query = query.filter(MediaFile.status == status)
    files = query.all()
    
    result_list = []
    for f in files:
        # Get latest audit result
        latest_res = db.query(AuditResult).filter(AuditResult.media_file_id == f.id).order_by(AuditResult.audited_at.desc()).first()
        res_data = None
        if latest_res:
            res_data = {
                "ffprobe_valid": latest_res.ffprobe_valid,
                "duration_actual": latest_res.duration_actual,
                "duration_variance": latest_res.duration_variance,
                "video_codec": latest_res.video_codec,
                "audio_codec": latest_res.audio_codec,
                "container_format": latest_res.container_format,
                "audio_tracks_info": latest_res.audio_tracks_info,
                "vlm_title_verified": latest_res.vlm_title_verified,
                "vlm_credits_verified": latest_res.vlm_credits_verified,
                "vlm_sanity_check_passed": latest_res.vlm_sanity_check_passed,
                "keyframes_paths": latest_res.keyframes_paths,
                "detected_languages": latest_res.detected_languages,
                "audio_transcript_snippet": latest_res.audio_transcript_snippet,
                "audio_clips_paths": latest_res.audio_clips_paths,
                "notes": latest_res.notes
            }
            
        result_list.append({
            "id": f.id,
            "filepath": f.filepath,
            "filename": f.filename,
            "title": f.title,
            "media_type": f.media_type,
            "expected_duration": f.expected_duration,
            "status": f.status,
            "added_at": f.added_at,
            "audit_result": res_data
        })
    return result_list

@app.post("/api/files/{file_id}/requeue")
def requeue_file(file_id: int, db: Session = Depends(get_db)):
    """Manually adds a file back to the audit queue."""
    media_file = db.query(MediaFile).filter(MediaFile.id == file_id).first()
    if not media_file:
        raise HTTPException(status_code=404, detail="File not found")
        
    media_file.status = FileStatus.PENDING
    
    # Create or update job
    job = AuditJob(
        media_file_id=media_file.id,
        status=JobStatus.PENDING
    )
    db.add(job)
    db.commit()
    return {"message": f"File {media_file.filename} requeued."}

# Mount static folder for dashboard
# Make sure to run this mount last so API endpoints take priority
app.mount("/", StaticFiles(directory=str(app_static_path), html=True), name="static")
