import os
from datetime import datetime
import asyncio
import logging
from fastapi import FastAPI, Depends, BackgroundTasks, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from pathlib import Path
from pydantic import BaseModel

from app.database import init_db, get_db, SessionLocal, MediaFile, AuditJob, AuditResult, JobStatus, FileStatus, SystemConfig
from app.queue_manager import worker
from app.scanner import MediaScanner
from app.plex_client import PlexClient

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger("main")

app = FastAPI(title="PlexScraper Media Verification Service")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Configuration values
SCAN_PATHS = os.environ.get("SCAN_PATHS", "./media").split(",")
WORKSPACE_ROOT = os.environ.get("WORKSPACE_ROOT", ".")

# Create directories if they do not exist
Path(WORKSPACE_ROOT).mkdir(parents=True, exist_ok=True)
for path in SCAN_PATHS:
    if path:
        Path(path).mkdir(parents=True, exist_ok=True)

# Mount Static assets
# Keyframes and audio clips generated by the media processor reside inside workspace/processed_media
processed_media_path = Path(WORKSPACE_ROOT) / "processed_media"
processed_media_path.mkdir(exist_ok=True)
(processed_media_path / "keyframes").mkdir(exist_ok=True)
(processed_media_path / "audio").mkdir(exist_ok=True)

app.mount("/static/media", StaticFiles(directory=str(processed_media_path)), name="media")

# We will mount dashboard UI files inside app/static
app_static_path = Path(__file__).parent / "static"
app_static_path.mkdir(exist_ok=True)

class ScanRequest(BaseModel):
    paths: list[str] | None = None

@app.on_event("startup")
def startup_event():
    init_db()
    worker.start()
    logger.info("Database initialized and queue worker spawned.")

@app.on_event("shutdown")
def shutdown_event():
    worker.stop()
    logger.info("Queue worker stopped.")

@app.get("/api/status")
def get_service_status():
    """Gets general statistics and pipeline state."""
    db = SessionLocal()
    try:
        from sqlalchemy import func
        # Query counts grouped by status in one call
        counts = db.query(MediaFile.status, func.count(MediaFile.id)).group_by(MediaFile.status).all()
        counts_dict = {status: count for status, count in counts}
        
        total_files = sum(counts_dict.values())
        verified_files = counts_dict.get(FileStatus.VERIFIED, 0)
        
        # Safely check for FLAGGED_ status
        flagged_files = sum(
            count for status, count in counts_dict.items() 
            if status and (
                (hasattr(status, "value") and status.value.startswith("FLAGGED_")) or
                (isinstance(status, str) and status.startswith("FLAGGED_"))
            )
        )
        
        pending_jobs = db.query(AuditJob).filter(AuditJob.status == JobStatus.PENDING).count()
        
        current_jobs = db.query(AuditJob).filter(AuditJob.status == JobStatus.PROCESSING).all()
        active_jobs = [
            {
                "id": j.id,
                "filename": j.media_file.filename if j.media_file else "Unknown"
            }
            for j in current_jobs if j.media_file
        ]

        return {
            "is_running": worker.is_running,
            "is_paused": worker.is_paused,
            "total_files": total_files,
            "verified_files": verified_files,
            "flagged_files": flagged_files,
            "pending_jobs_count": pending_jobs,
            "active_jobs": active_jobs
        }
    finally:
        db.close()

@app.get("/api/pipeline/failures-log")
def get_failures_log():
    """Retrieves the plain text contents of failures.log."""
    log_path = Path(WORKSPACE_ROOT) / "data" / "failures.log"
    if not log_path.exists():
        return {"log": "No failures logged yet."}
    try:
        with open(log_path, "r", encoding="utf-8") as f:
            return {"log": f.read()}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to read failures log: {str(e)}")

class ConfigUpdateRequest(BaseModel):
    max_concurrent_jobs: int
    ffmpeg_threads: int

@app.get("/api/pipeline/config")
def get_pipeline_config(db: Session = Depends(get_db)):
    """Retrieves current in-memory / database system config parameters."""
    max_concurrent = db.query(SystemConfig).filter(SystemConfig.key == "MAX_CONCURRENT_JOBS").first()
    ffmpeg_threads = db.query(SystemConfig).filter(SystemConfig.key == "FFMPEG_THREADS").first()
    
    return {
        "max_concurrent_jobs": int(max_concurrent.value) if max_concurrent else int(os.environ.get("MAX_CONCURRENT_JOBS", "3")),
        "ffmpeg_threads": int(ffmpeg_threads.value) if ffmpeg_threads else int(os.environ.get("FFMPEG_THREADS", "1"))
    }

@app.post("/api/pipeline/config")
def update_pipeline_config(config: ConfigUpdateRequest, db: Session = Depends(get_db)):
    """Saves new settings preferences to database and applies them in-memory immediately."""
    try:
        # Update SQLite DB records
        for key, val in [("MAX_CONCURRENT_JOBS", str(config.max_concurrent_jobs)), ("FFMPEG_THREADS", str(config.ffmpeg_threads))]:
            record = db.query(SystemConfig).filter(SystemConfig.key == key).first()
            if not record:
                record = SystemConfig(key=key, value=val)
                db.add(record)
            else:
                record.value = val
        db.commit()
        
        # Apply in-memory variables immediately to active process environment
        os.environ["MAX_CONCURRENT_JOBS"] = str(config.max_concurrent_jobs)
        os.environ["FFMPEG_THREADS"] = str(config.ffmpeg_threads)
        
        logger.info(f"System settings updated. Max jobs: {config.max_concurrent_jobs}, FFmpeg threads: {config.ffmpeg_threads}")
        return {"message": "System config settings updated successfully."}
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=f"Failed to update settings: {str(e)}")

@app.post("/api/pipeline/pause")
def pause_pipeline():
    worker.pause()
    return {"message": "Pipeline paused."}

@app.post("/api/pipeline/resume")
def resume_pipeline():
    worker.resume()
    return {"message": "Pipeline resumed."}

@app.post("/api/pipeline/scan")
def trigger_filesystem_scan(request: ScanRequest = None, db: Session = Depends(get_db)):
    """Triggers crawler to scan designated folders for new files."""
    paths = request.paths if request and request.paths else SCAN_PATHS
    scanner = MediaScanner(media_directories=paths)
    new_files = scanner.scan_and_register_files(db)
    
    # Enrich metadata from Plex if configured
    plex = PlexClient()
    new_media_records = db.query(MediaFile).filter(MediaFile.plex_rating_key == None).all()
    if new_media_records:
        # Build path map in a single pass
        import os
        plex_map = plex.get_all_paths_mapping()
        if plex_map:
            for item in new_media_records:
                norm_path = os.path.normpath(item.filepath)
                if norm_path in plex_map:
                    duration, rating_key = plex_map[norm_path]
                    item.expected_duration = duration
                    item.plex_rating_key = rating_key
            db.commit()

    return {"message": f"Scan completed. Discovered and queued {new_files} new files."}

@app.get("/api/files")
def get_files(
    status: str | None = None, 
    page: int = 1, 
    page_size: int = 20, 
    search: str | None = None,
    sort_by: str | None = "added_at",
    sort_order: str | None = "desc",
    db: Session = Depends(get_db)
):
    """Retrieves tracked media files with pagination, search, and sorting parameters."""
    try:
        query = db.query(MediaFile)
        
        # Apply filters
        if status:
            if status.startswith("FLAGGED"):
                query = query.filter(MediaFile.status.like("FLAGGED_%"))
            else:
                query = query.filter(MediaFile.status == status)
                
        if search:
            query = query.filter(MediaFile.filename.like(f"%{search}%"))
            
        # Get total count for UI pagination details
        total_count = query.count()
        
        # Apply Sorting
        # For sorting by confidence, we need to join the latest AuditResult
        if sort_by == "confidence":
            from app.database import AuditResult
            from sqlalchemy import func
            
            # Subquery to get latest audit result per media file
            subq = db.query(
                AuditResult.media_file_id,
                func.max(AuditResult.audited_at).label("max_audited_at")
            ).group_by(AuditResult.media_file_id).subquery()
            
            # Join query with AuditResult
            query = query.outerjoin(
                AuditResult, 
                (MediaFile.id == AuditResult.media_file_id)
            ).outerjoin(
                subq,
                (AuditResult.media_file_id == subq.c.media_file_id) &
                (AuditResult.audited_at == subq.c.max_audited_at)
            )
            
            if sort_order == "asc":
                # Standard ascending sort
                query = query.order_by(AuditResult.confidence_score.asc())
            else:
                # Standard descending sort
                query = query.order_by(AuditResult.confidence_score.desc())
        else:
            # Default sorting by added_at
            if sort_order == "asc":
                query = query.order_by(MediaFile.added_at.asc())
            else:
                query = query.order_by(MediaFile.added_at.desc())

        # Apply pagination offsets
        offset = (page - 1) * page_size
        from sqlalchemy.orm import joinedload
        files = query.options(joinedload(MediaFile.results)).offset(offset).limit(page_size).all()
        
        result_list = []
        for f in files:
            # Get latest audit result from preloaded list in memory to avoid queries
            latest_res = None
            if f.results:
                # Sort preloaded results list in memory
                sorted_res = sorted(f.results, key=lambda r: r.audited_at, reverse=True)
                latest_res = sorted_res[0]
                
            res_data = None
            if latest_res:
                res_data = {
                    "ffprobe_valid": latest_res.ffprobe_valid,
                    "duration_actual": latest_res.duration_actual,
                    "duration_variance": latest_res.duration_variance,
                    "video_codec": latest_res.video_codec,
                    "audio_codec": latest_res.audio_codec,
                    "container_format": latest_res.container_format,
                    "audio_tracks_info": latest_res.audio_tracks_info,
                    "vlm_title_verified": latest_res.vlm_title_verified,
                    "vlm_credits_verified": latest_res.vlm_credits_verified,
                    "vlm_sanity_check_passed": latest_res.vlm_sanity_check_passed,
                    "keyframes_paths": latest_res.keyframes_paths,
                    "detected_languages": latest_res.detected_languages,
                    "audio_transcript_snippet": latest_res.audio_transcript_snippet,
                    "audio_clips_paths": latest_res.audio_clips_paths,
                    "confidence_score": latest_res.confidence_score,
                    "notes": latest_res.notes
                }
                
            result_list.append({
                "id": f.id,
                "filepath": f.filepath,
                "filename": f.filename,
                "title": f.title,
                "media_type": f.media_type,
                "expected_duration": f.expected_duration,
                "status": f.status,
                "added_at": f.added_at,
                "audit_result": res_data
            })
            
        return {
            "total_items": total_count,
            "page": page,
            "page_size": page_size,
            "items": result_list
        }
    except Exception as e:
        logger.error(f"Error fetching files: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/files/{file_id}/requeue")
def requeue_file(file_id: int, db: Session = Depends(get_db)):
    """Manually adds a file back to the audit queue."""
    media_file = db.query(MediaFile).filter(MediaFile.id == file_id).first()
    if not media_file:
        raise HTTPException(status_code=404, detail="File not found")
        
    media_file.status = FileStatus.PENDING
    
    # Create or update job
    job = AuditJob(
        media_file_id=media_file.id,
        status=JobStatus.PENDING
    )
    db.add(job)
    db.commit()
    return {"message": f"File {media_file.filename} requeued."}

@app.post("/api/pipeline/requeue-by-status")
def requeue_by_status(status: str, db: Session = Depends(get_db)):
    """Bulk resets the status of all files matching a specific state and adds them back to the queue."""
    # Find matching files
    files = db.query(MediaFile).filter(MediaFile.status == status).all()
    if not files:
        return {"message": f"No files found with status '{status}'."}
        
    # Requeue each file
    count = 0
    for f in files:
        f.status = FileStatus.PENDING
        job = AuditJob(
            media_file_id=f.id,
            status=JobStatus.PENDING
        )
        db.add(job)
        count += 1
        
    db.commit()
    # Trigger worker to ensure it starts processing
    worker.start()
    return {"message": f"Successfully requeued {count} files in status '{status}'."}

@app.post("/api/files/{file_id}/manual-verify")
def manual_verify_file(file_id: int, db: Session = Depends(get_db)):
    """Manually marks a file as verified."""
    media_file = db.query(MediaFile).filter(MediaFile.id == file_id).first()
    if not media_file:
        raise HTTPException(status_code=404, detail="File not found")
        
    media_file.status = FileStatus.VERIFIED
    
    # Check if there is an AuditResult, or create a new one
    result = db.query(AuditResult).filter(AuditResult.media_file_id == file_id).order_by(AuditResult.audited_at.desc()).first()
    if not result:
        result = AuditResult(media_file_id=file_id)
        db.add(result)
        
    result.status = FileStatus.VERIFIED
    result.confidence_score = 100
    result.notes = "Manually verified by user."
    result.audited_at = datetime.utcnow()
    
    # Clean any pending jobs for this file
    db.query(AuditJob).filter(AuditJob.media_file_id == file_id, AuditJob.status == JobStatus.PENDING).delete()
    
    db.commit()
    return {"message": f"File {media_file.filename} manually verified."}

@app.post("/api/files/{file_id}/manual-flag")
def manual_flag_file(file_id: int, db: Session = Depends(get_db)):
    """Manually marks a file as flagged/incorrect."""
    media_file = db.query(MediaFile).filter(MediaFile.id == file_id).first()
    if not media_file:
        raise HTTPException(status_code=404, detail="File not found")
        
    media_file.status = FileStatus.FLAGGED_TITLE
    
    # Check if there is an AuditResult, or create a new one
    result = db.query(AuditResult).filter(AuditResult.media_file_id == file_id).order_by(AuditResult.audited_at.desc()).first()
    if not result:
        result = AuditResult(media_file_id=file_id)
        db.add(result)
        
    result.status = FileStatus.FLAGGED_TITLE
    result.confidence_score = 0
    result.notes = "Manually flagged as incorrect by user."
    result.audited_at = datetime.utcnow()
    
    # Clean any pending jobs for this file
    db.query(AuditJob).filter(AuditJob.media_file_id == file_id, AuditJob.status == JobStatus.PENDING).delete()
    
    db.commit()
    return {"message": f"File {media_file.filename} manually flagged."}

def clean_physical_assets():
    # Remove physical files from keyframes and audio dirs
    kf_dir = Path(WORKSPACE_ROOT) / "processed_media" / "keyframes"
    audio_dir = Path(WORKSPACE_ROOT) / "processed_media" / "audio"
    
    for folder in [kf_dir, audio_dir]:
        if folder.exists():
            for item in folder.iterdir():
                if item.is_file():
                    try:
                        item.unlink()
                    except Exception as e:
                        logger.error(f"Error removing cached file {item}: {e}")

@app.post("/api/pipeline/nuke/queue")
def nuke_queue_and_reset(background_tasks: BackgroundTasks, db: Session = Depends(get_db)):
    """Deletes jobs, results, resets files to PENDING, recreates jobs, and cleans assets in background."""
    was_running = worker.is_running
    worker.stop()
    try:
        # Delete jobs and results
        db.query(AuditJob).delete()
        db.query(AuditResult).delete()
        
        # Reset media files to pending status
        db.query(MediaFile).update({MediaFile.status: FileStatus.PENDING})
        db.commit()
        
        # Recreate pending jobs for all media files in bulk
        media_file_ids = [r[0] for r in db.query(MediaFile.id).all()]
        if media_file_ids:
            jobs = [AuditJob(media_file_id=mf_id, status=JobStatus.PENDING) for mf_id in media_file_ids]
            db.bulk_save_objects(jobs)
            db.commit()
            
        background_tasks.add_task(clean_physical_assets)
        return {"message": f"Queue reset complete. Wiped results and re-queued {len(media_file_ids)} files."}
    finally:
        if was_running:
            worker.start()

@app.post("/api/pipeline/nuke/states")
def clear_verification_states(background_tasks: BackgroundTasks, db: Session = Depends(get_db)):
    """Wipes all audit logs, job history, sets files to PENDING, and stops the queue processor."""
    worker.stop()
    try:
        # Delete jobs and results
        db.query(AuditJob).delete()
        db.query(AuditResult).delete()
        
        # Reset media files to pending status
        db.query(MediaFile).update({MediaFile.status: FileStatus.PENDING})
        db.commit()
        
        background_tasks.add_task(clean_physical_assets)
        return {"message": "Verification states cleared. Queue paused and all files reset to pending."}
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=f"Failed to clear states: {str(e)}")

@app.post("/api/pipeline/nuke/database")
def nuke_database_full(background_tasks: BackgroundTasks, db: Session = Depends(get_db)):
    """Deletes all media files, jobs, results, and triggers async asset deletion."""
    was_running = worker.is_running
    worker.stop()
    try:
        db.query(AuditJob).delete()
        db.query(AuditResult).delete()
        db.query(MediaFile).delete()
        db.commit()
        
        background_tasks.add_task(clean_physical_assets)
        return {"message": "Full database wipe completed. All registered files and results deleted."}
    finally:
        if was_running:
            worker.start()

@app.post("/api/pipeline/nuke")
def nuke_all_pipeline_data(background_tasks: BackgroundTasks, db: Session = Depends(get_db)):
    """Deprecated alias for nuke/database."""
    return nuke_database_full(background_tasks, db)

# Mount static folder for dashboard
# Make sure to run this mount last so API endpoints take priority
app.mount("/", StaticFiles(directory=str(app_static_path), html=True), name="static")
